# Site settings
title: "On Mathematics, Computer Science Theory, and AI"
author: "Uros Nedic"
description: "This is a blog about computer science theory, some mathematics, and the ai. Not necessarily in that order."
keywords: "Software Engineering, Computer Science Theory Mathematics, Haskell, Scala, Programming, Machine-Learning, Artificial Intelligence"
biography: "I am a Software Engineer and a human being."
colophon: "© MMXVI — MMXVII by Uros Nedic. Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/''>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>"

baseurl: ""
url: "http://urosn.github.io"

twitter_username: urosn
github_username: urosn
linkedin_username: urosn
# facebook_username: hugo.sereno.ferreira
# instagram_username: hugo.sereno.ferreira
# 500px_username: hugoserenoferreira

google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

gems:
- jekyll-sitemap
